const truffleAssert = require("truffle-assertions");

const Factory = artifacts.require("ZombieFactory");
const Zombie = artifacts.require("Zombie");

const {
  createAddress2,
  numberToUint256,
  encodeParam,
  isDeployed,
} = require("./utils/utils.js");

contract("ZombieFactory", async (accounts) => {
  const {
    abi: zombieABI,
    bytecode: zombieBytecode,
  } = require("../build/contracts/Zombie.json");
  const name1 = "Gildong";
  const name2 = "Chulsoo";

  before(async () => {
    zombieFactory = await Factory.new({ from: accounts[0] });
  });

  describe("Zombie generated by 'create'", () => {
    it("두 좀비의 주소가 달라야 합니다.", async () => {
      await truffleAssert.passes(await zombieFactory.createRandomZombie(name1));

      const zombie1Addr = await zombieFactory.zombies(0);
      const zombie1 = await Zombie.at(zombie1Addr);
      let name = await zombie1.name();
      let dna = await zombie1.dna();
      console.log("Zombie generated:", zombie1Addr, name, +dna);

      await truffleAssert.passes(await zombieFactory.createRandomZombie(name2));

      const zombie2Addr = await zombieFactory.zombies(1);
      const zombie2 = await Zombie.at(zombie2Addr);
      name = await zombie2.name();
      dna = await zombie2.dna();
      console.log("Zombie generated:", zombie2Addr, name, +dna);

      await assert.notStrictEqual(zombie1Addr, zombie2Addr);
    });
  });

  describe("Zombie generated by 'create2'", () => {
    beforeEach(async () => {
      await truffleAssert.passes(
        await zombieFactory.createRandomZombieV2(name1)
      );
    });
    it("좀비의 주소가 미리 특정한 주소와 같아야 합니다.", async () => {});
    it("이름이 다른 두 좀비의 주소가 달라야 합니다.", async () => {});
    it("이름이 같은 두 좀비의 주소가 같아야 합니다.", async () => {});
    it("selfdestruct", async () => {});
  });
});
